// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";

export type CreateAvailabilityRange = {
  rangeStart: string,
  rangeEnd: string,
  availabilityLevel: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace CreateAvailabilityRange {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("rangeStart", AlgebraicType.createStringType()),
      new ProductTypeElement("rangeEnd", AlgebraicType.createStringType()),
      new ProductTypeElement("availabilityLevel", AlgebraicType.createI8Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: CreateAvailabilityRange): void {
    CreateAvailabilityRange.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): CreateAvailabilityRange {
    return CreateAvailabilityRange.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

